### ISSUE TITLE
new feature : No RSS generation support for the blog

### ISSUE THREAD

**Issue by bcopy** [sysgears/grain-theme-business#1]
There's no RSS generation feature for the blog, would it be possible to add one ?

Where could I get started if I wanted to write one ?

**Comment by larixer** [comment]
Hi Brice,

I believe RSS code from Grain Octopress theme should work with this theme mostly as is:
https://github.com/sysgears/grain-theme-octopress/blob/master/content/atom.xml
https://github.com/sysgears/grain-theme-octopress/blob/master/theme/includes/head.html#L19

If you want RSS per post category, then you will also need to adapt this code:
https://github.com/sysgears/grain-theme-octopress/blob/master/theme/src/com/sysgears/octopress/mapping/ResourceMapper.groovy#L152-L164

**Comment by bcopy** [comment]
Hi Victor,

I placed the atom.xml in my content, generation goes okay (changed the xml
date format to just dump a string it's okay) but :

page.posts
And
page

Are both empty.
What am I missing ?
Brice

**Comment by larixer** [comment]
Yes, you need to modify ResourceMapper of Business Theme to make 'posts' available in atom.xml

``` groovy
    private def customizeModels = { List resources ->
        def posts = resources.findAll { it.layout == 'post' }
        ...
                case '/atom.xml':
                    int maxRss = 10
                    def lastUpdated = new Date(posts.max { it.updated.time }.updated.time as Long)

                    // Here we inject 'posts' variable into model of '/atom.xml'
                    updatedResources << (page + [posts: posts.take(10), lastUpdated: lastUpdated])
                    break
```

**Comment by bcopy** [comment]
Thanks a lot, will submit a merge request !

**Comment by larixer** [comment]
That would be fantastic!
