### ISSUE TITLE
Bug : When the deployment website is not at the root, the NEXT and PREVIOUS blog button fail

### ISSUE THREAD

**Issue by bcopy** [sysgears/grain-theme-business#3]
Testcase :
- Update SiteConfig.groovy and set the environments.prod.url property to a URL with a sub-folder at the root, for instance http://mydomain.com/mysite
- Generate the website with `./grainw generate`
- Go to any generated blog page, the NEXT and PREVIOUS button URLs are not including the /mysite prefix and point to invalid addresses.
  - For instance, go to `blog/posts/post-1-title/index.html`
  -  The link
    - `<a href="/blog/posts/post-2-title/">Older &rarr;</a>` 
  - should actually point to :
    - a href="/**mysite**/blog/posts/post-2-title/"

**Comment by 23shortstop** [comment]
Fixed by using link tag from the basic tag lib of Grain framework.
We'll update Grain docs with description of this tag soon.
